In [1]:
import numpy as np

arr = np.array([1, 2, 3, 84, 55, 16, 7])

print(arr[1:4])

[ 2  3 84]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:]) #slice elements from index 4 to the end of the array:

[5 6 7]


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])


[1 2 3 4]


In [5]:
#Negative Slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-2:-1])

[6]


In [6]:
#Use the step value to determine the step of the slicing:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [7]:
#Slicing 2-D Arrays
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])            #1 is the index for [6,7,8,9,0]

print(arr[1, 1:4])

[7 8 9]
